function generateRizz() {
        let arrayQuotes = [
            'Are you a magician? Because whenever I look at you, everyone else disappears', 
            'Do you have a name, or can I call you mine?', 
            'Is your name Wi-Fi? Because I’m feeling a connection.', 
            'If beauty were time, you’d be eternity.', 
            'Are you a camera? Every time I look at you, I smile.', 
            'You must be a spark, because you just lit up my whole day.',
            'Is your vibe always this magnetic or am I just lucky tonight?',
            'If confidence was a crime, you’d be serving a life sentence.',
            'You walk in like you own the place—teach me how to do that.',
            'Did we just share a glance or did time actually slow down?',
            'Your energy is the kind of contagious I don’t mind catching.',
            'If charm was currency, you’d be the richest person in the room.',
            'I didn’t believe in fate until I bumped into you.',
            'You’ve got the kind of presence that makes everyone level up.',
            'Are you always this captivating, or is tonight special?',
            'Do you have a map? I just got lost in your eyes.', 
            'If you were a vegetable, you’d be a cute-cumber.', 
            'Excuse me, but I think you dropped something: my jaw.', 
            'Are you made of copper and tellurium? Because you’re Cu-Te.', 
            'If you were a fruit, you’d be a fine-apple.',
            'If being smooth was an Olympic sport, you’d have all the gold medals.',
            'You’re the reason the stars come out at night.',
            'I must be a snowflake, because I’ve fallen for you.',
            'You make ordinary moments feel extraordinary.',
            'If I had a star for every time you brightened my day, I’d have a galaxy.',
            'You’re the plot twist I never saw coming.',
            'If I could rearrange the alphabet, I’d put U and I together.',
            'You’re the kind of person songs are written about.',
            'If I had a nickel for every time I thought of you, I’d be rich by now.',
            'You make the world feel a little less ordinary.',
            'If I were to write a story, you’d be my favorite chapter.',
            'You’re the reason I check my phone with a smile.',
            'If charm was a superpower, you’d be unstoppable.',
        'You make every room brighter just by walking in.',
        'If I could bottle your energy, I’d never need coffee again.',
        'You’re the highlight of my day, every day.',
        'If I had to choose between breathing and loving you, I’d use my last breath to say I love you.',
        'You’re the kind of vibe I want to be around all the time.',
        'If I could paint a picture of perfection, it’d look a lot like you.',
        'You’re the reason I believe in good luck.',
        'If I had a dollar for every time you crossed my mind, I’d own the bank.',
        'You’re the melody to my favorite song.',
        'If I could wish for anything, I’d wish for more moments with you.',
        'You’re the spark that lights up my world.',
        'If I could hold time still, I’d pause it every time I’m with you.',
        'You’re the reason I look forward to tomorrow.',
        'If I could write you a poem, it’d never end.',
        'You’re the kind of rare that people search a lifetime for.',
        'If I could capture happiness, it’d look just like you.',
        'You’re the answer to questions I didn’t know I had.',
        ]
        let randomNum = Math.floor(Math.random() * arrayQuotes.length)
        document.getElementById('rizztext').textContent = arrayQuotes[randomNum]

    }