function generateRizz() {
        let arrayQuotes = [
                        'Are you a magician? Because whenever I look at you, everyone else disappears', 
            'Do you have a name, or can I call you mine?', 
            'Is your name Wi-Fi? Because I’m feeling a connection.', 
            'If beauty were time, you’d be eternity.', 
            'Are you a camera? Every time I look at you, I smile.', 
            'You must be a spark, because you just lit up my whole day.',
            'Is your vibe always this magnetic or am I just lucky tonight?',
            'If confidence was a crime, you’d be serving a life sentence.',
            'You walk in like you own the place—teach me how to do that.',
            'Did we just share a glance or did time actually slow down?',
            'Your energy is the kind of contagious I don’t mind catching.',
            'If charm was currency, you’d be the richest person in the room.',
            'I didn’t believe in fate until I bumped into you.',
            'You’ve got the kind of presence that makes everyone level up.',
            'Are you always this captivating, or is tonight special?',
            'Do you have a map? I just got lost in your eyes.', 
            'If you were a vegetable, you’d be a cute-cumber.', 
            'Excuse me, but I think you dropped something: my jaw.', 
            'Are you made of copper and tellurium? Because you’re Cu-Te.', 
            'If you were a fruit, you’d be a fine-apple.',
            'If being smooth was an Olympic sport, you’d have all the gold medals.',
            'You’re the reason the stars come out at night.',
            'I must be a snowflake, because I’ve fallen for you.',
            'You make ordinary moments feel extraordinary.',
            'If I had a star for every time you brightened my day, I’d have a galaxy.',
            'You’re the plot twist I never saw coming.',
            'If I could rearrange the alphabet, I’d put U and I together.',
            'You’re the kind of person songs are written about.',
            'If I had a nickel for every time I thought of you, I’d be rich by now.',
            'You make the world feel a little less ordinary.',
            'If I were to write a story, you’d be my favorite chapter.',
            'You’re the reason I check my phone with a smile.',
            'If charm was a superpower, you’d be unstoppable.',
        'You make every room brighter just by walking in.',
        'If I could bottle your energy, I’d never need coffee again.',
        'You’re the highlight of my day, every day.',
        'If I had to choose between breathing and loving you, I’d use my last breath to say I love you.',
        'You’re the kind of vibe I want to be around all the time.',
        'If I could paint a picture of perfection, it’d look a lot like you.',
        'You’re the reason I believe in good luck.',
        'If I had a dollar for every time you crossed my mind, I’d own the bank.',
        'You’re the melody to my favorite song.',
        'If I could wish for anything, I’d wish for more moments with you.',
        'You’re the spark that lights up my world.',
        'If I could hold time still, I’d pause it every time I’m with you.',
        'You’re the reason I look forward to tomorrow.',
        'If I could write you a poem, it’d never end.',
        'You’re the kind of rare that people search a lifetime for.',
        'If I could capture happiness, it’d look just like you.',
        'You’re the answer to questions I didn’t know I had.',
        'If being cool was a crime, you’d be on the most wanted list.',
        ' Do you have a sun? Because you just brightened up my day.',
        ' If I had a dollar for every time I thought of you, I’d be a millionaire by now.',
        ' Are you a secret agent? Because you just snuck into my heart.',
        ' If you were a math problem, I’d always try to solve you.',
        ' Are you a campfire? Because you bring everyone together.',
        ' If you were a phone, I’d never put you on silent.',
        ' Are you a legend? Because your story is unforgettable.',
        ' If you were a mystery, I’d never want to find the answer.',
        ' Are you a sunrise? Because you make every morning worth waking up for.',
        ' If you were a playlist, you’d be on repeat all day.',
        ' Are you a rare find? Because I feel lucky just talking to you.',
        ' If you were a dream, I’d hit snooze just to stay with you longer.',
        ' Are you a good luck charm? Because things just got better when you showed up.',
        ' If you were a joke, you’d be the one everyone remembers.',
        ' Are you a spark? Because you started something in me I can’t explain.',
        ' If you were a page, you’d be the one I’d never want to turn.',
        ' Are you a wish? Because I didn’t know I needed you until now.',
        ' If you were a vibe, you’d be the one everyone wants to catch.',
        ' Are you a story? Because I want to know every chapter.',
        ' If you were a password, you’d be impossible to forget.',
        ' Are you a melody? Because you’re stuck in my head.',
        ' If you were a star, you’d outshine the rest.',
        ' Are you a secret? Because I want to keep you all to myself.',
        ' If you were a meme, you’d be the one everyone shares.',
        ' Are you a compass? Because you always point me in the right direction.',
        ' If you were a color, you’d be the one that makes everything pop.',
        ' Are you a snowflake? Because you’re one of a kind.',
        ' If you were a season, you’d be the best part of the year.',
        ' Are you a high score? Because I keep trying to reach you.',
        ' If you were a poem, you’d be the line I’d never forget.',
        ' Are you a light? Because you make everything clearer.',
        ' If you were a snack, you’d be the one I can’t resist.',
        ' Are you a goal? Because I can’t stop aiming for you.',
        ' If you were a trend, you’d never go out of style.',
        ' Are you a secret menu item? Because you’re not easy to find, but totally worth it.',
        ' If you were a planet, you’d be the center of my universe.',
        ' Are you a rare Pokémon? Because I’d travel anywhere to find you.',
        ' If you were a movie, you’d be the one I’d watch over and over.',
        ' Are you a spark? Because you light up my world.',
        ' If you were a challenge, I’d never give up on you.',
        ' Are you a sunrise? Because you make every day feel new.',
        ' If you were a song, you’d be my favorite track.',
        ' Are you a wish? Because you’re what I’ve been hoping for.',
        ' If you were a game, you’d be the one I’d never want to quit.',
        ' Are you a highlight? Because you make every moment better.',
        ' If you were a secret, you’d be the one I’d never tell.',
        ' Are you a bookmark? Because you keep my place in this story.',
        ' If you were a superpower, you’d be making people smile.',
        ' Are you a rare gem? Because you’re priceless.',
        ' If you were a headline, you’d be the one everyone’s talking about.',
        'You’re the answer to questions I didn’t know I had.',
        ]
        let randomNum = Math.floor(Math.random() * arrayQuotes.length)
        document.getElementById('rizztext').textContent = arrayQuotes[randomNum]

    }
